  - name: Install etcd
    apt:
      name: etcd
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Enable etcd
    systemd:
      name: etcd
      enabled: yes

